# Generated by Django 5.1.6 on 2025-03-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('legal_bases', models.CharField(max_length=10)),
                ('description', models.TextField(max_length=255)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('driver_fine', models.DecimalField(decimal_places=2, max_digits=10)),
                ('owner_fine', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eu_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Violator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=20, unique=True)),
                ('datetime_inspection', models.DateTimeField()),
                ('name', models.CharField(max_length=50)),
                ('kind_violation', models.CharField(choices=[('Οδηγός', 'Οδηγός'), ('Ιδιοκτήτης', 'Ιδιοκτήτης')], default='Οδηγός', max_length=10)),
                ('code_violation', models.CharField(max_length=10)),
                ('date_violation', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
