# Generated by Django 5.1.6 on 2025-03-05 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='violation',
            old_name='legal_bases',
            new_name='legal_basis',
        ),
    ]
