# Generated by Django 5.1.6 on 2025-03-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0002_rename_legal_bases_violation_legal_basis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='driver_fine',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='violation',
            name='eu_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='violation',
            name='owner_fine',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='violator',
            name='kind_violation',
            field=models.CharField(choices=[('Οδηγός', 'Οδηγός'), ('Ιδιοκτήτης', 'Ιδιοκτήτης')], default='Ιδιοκτήτης', max_length=10),
        ),
    ]
