# Generated by Django 5.1.6 on 2025-03-05 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0003_alter_violation_driver_fine_alter_violation_eu_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='violation',
            name='description',
        ),
    ]
