# Generated by Django 5.1.6 on 2025-03-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0004_remove_violation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='driver_fine',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='violation',
            name='owner_fine',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
