# Generated by Django 5.1.6 on 2025-03-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0005_alter_violation_driver_fine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='driver_fine',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='violation',
            name='owner_fine',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
