# Generated by Django 5.1.6 on 2025-03-06 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0006_alter_violation_driver_fine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='violator',
            name='code_violation',
        ),
        migrations.RemoveField(
            model_name='violator',
            name='date_violation',
        ),
        migrations.RemoveField(
            model_name='violator',
            name='datetime_inspection',
        ),
        migrations.RemoveField(
            model_name='violator',
            name='kind_violation',
        ),
        migrations.AddField(
            model_name='violation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ViolationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_inspection', models.DateTimeField()),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('kind_violation', models.CharField(choices=[('Οδηγός', 'Οδηγός'), ('Ιδιοκτήτης', 'Ιδιοκτήτης')], default='Ιδιοκτήτης', max_length=10)),
                ('violation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='violations.violation')),
                ('violator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='violations.violator')),
            ],
        ),
        migrations.AddField(
            model_name='violator',
            name='violations',
            field=models.ManyToManyField(related_name='violators', through='violations.ViolationRecord', to='violations.violation'),
        ),
    ]
