# Generated by Django 5.1.6 on 2025-03-06 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0007_remove_violator_code_violation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='violator',
            old_name='license_number',
            new_name='circulation_number',
        ),
    ]
