# Generated by Django 5.1.6 on 2025-03-09 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0009_rename_kind_violation_violationrecord_kind_violator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='violationrecord',
            name='date_recorded',
        ),
    ]
